### PR TITLE
Added an optional CDN service and optimized the code

### PR DESCRIPTION
**Pull request by AH-dark**
I originally wanted to use VMware to build a virtual machine environment for testing (because I don't have a Typecho testing environment), but it is too fucking slow and I can't wait for it.

---

This Pull Request mainly contains the following modifications

- Added [Source Storage CDN](https://ahdark.com/source/) option and added version number for jsDelivr CDN in `libs/G.class.php`.
- Formated the code to make it more standard and more comfortable.
- Compress some uncompressed JavaScript and CSS files.
- Use Less to reconstruct the original `static/css/G.css` to make style development more comfortable and convenient.
- Changed the `lib` directory name to `libs`. (what the fuck?)

You need to pay attention to

- Less is easy to learn and shows a clearer structure.
- When Typecho is not in Debug mode, it will load the compressed css/js with `.min` infix. When it's on, it will load the original uncompressed css/js.

---

This is an optional Pull Request. 
If you think there is something you don't need, you can close this Pull Request and select the required part according to the code. 
In any case, Source Storage will include G theme and keep updating for it.

The corresponding URL directory is on `https://source.ahdark.com/typecho/theme/G/{version}/`.
You can refer https://ahdark.com/source/ for more informations.

---

P.S. This fucking slow installation process:

### CODE REVIEW

**Comment by AH-dark** [comment]
懒得测试了，悠然大佬你去测吧😉

**Comment by youranreus** [comment]
牛👍，我发布下一个版本的时候一起合并了

**Comment by GouGoBy** [comment]
围观

**Comment by AH-dark** [comment]
经实际测试，目前未发现问题

**Pull request merged**
